{% set name = "translationstring" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf947538d76e69ba12ab17283b10355a9ecfbc078e6123443f43f2107f6376f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - translationstring
    - translationstring.tests

about:
  home: http://pylonsproject.org
  license: BSD-like
  license_family: BSD
  license_file: LICENSE.txt
  summary: Utility library for i18n relied on by various Repoze and Pyramid packages
  doc_url: https://docs.pylonsproject.org/projects/translationstring/
  dev_url: https://github.com/Pylons/translationstring

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
