travis:
  secure:
    BINSTAR_TOKEN: F2d3IytWYeVjO+mk4Bvs10IP6HkIyzoVsgYdbqqR7RATWRNISbA5/4Ev3Wz6ZpJPvvzEQupGyAktaxdV/s+ZWXzLs5lrGuBQL2KZFIj/C08rcgq3HusHOLX8cu3H3Wn5cmxkO1Ke+e1LLOZPwQnZzM+nnL651lJZJMsHVtYH7zFXKZSw4dWV+KwXARs+A4YN45rWJ6FL4V2ACmJJNJqAbTor3tXvnKadnqdzmFHOj/5v5GHY1LiSZmWYxZpxFK5uNGfS6cBvbq1JZW3zBgU2XVCM8mFgy3p2a10kQrkIW2cOM+q0LuxZQejxV4CmHucP+6cyrOOCkE2oc3nfCb6OWX+2Qp1Dp+tPtYCxEHiRjp2r/RW+wM+htspSF92ZwPaKzEvwYlZ5Bsre3SAME0MNydZNaDx9OdXfWWRb1LS62s5IGPeTzU/s1VUmNFtsyQMQA7fgeuiv6c2hMobXWSuUDP4zwjSN5vinDEL21anupYSFYdrSkAFRHOAyWqXUVlyhHBB4Ie3qcA0fOqFNDU4z7t+zDJwhkeOjuLNhn52CZHG/qayXaefY967rDnzhzGt6yBNpnZ7NPyyn124XdWTH+bl5lJntfsX5f7tUhOyLwJKAxTbYKlkRi0dAWJh3GDPNh6KweIuTUTUUSI0k74H/Jy2zRyjAk4sRVbAzq39/D4w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
